name: default
channels:
    - conda-forge
dependencies:
    - python=2.7
    - eofs
    - gsw
    - iris
    - jupyter
    - pandas
    - scipy
    - seaborn
    - xarray
    - dask
    - bottleneck
    - netCDF4=1.2.4
    - statsmodels    
    - pip:
      - gitpython
