name: default
channels:
    - ioos
dependencies:
    - python=2.7
    - eofs
    - gsw
    - iris
    - jupyter
    - pandas
    - scipy
    - seaborn
    - xarray
    - dask
    - bottleneck
    - netCDF4    
    - pip:
      - gitpython
