/usr/local/anaconda/bin/python plot_map.py 2 3 \
--infile /mnt/meteo0/data/simmonds/dbirving/temp/sf-composite_wave7phase_9-19.nc streamfunction_JJA none none none contour0 1 PlateCarree \
--infile /mnt/meteo0/data/simmonds/dbirving/temp/sf-composite_wave7phase_29-39.nc streamfunction_JJA none none none contour0 2 PlateCarree \
--infile /mnt/meteo0/data/simmonds/dbirving/temp/sf-composite_wave7phase_43-52.nc streamfunction_JJA none none none contour0 3 PlateCarree \
--infile /mnt/meteo0/data/simmonds/dbirving/temp/sf-composite_wave7phase_9-19.nc streamfunction_JJA none none none contour0 4 PlateCarree \
--infile /mnt/meteo0/data/simmonds/dbirving/temp/sf-composite_wave7phase_29-39.nc streamfunction_JJA none none none contour0 5 PlateCarree \
--infile /mnt/meteo0/data/simmonds/dbirving/temp/sf-composite_wave7phase_43-52.nc streamfunction_JJA none none none contour0 6 PlateCarree \
--contour_levels -9 -7.5 -6 -4.5 -3 -1.5 0 1.5 3 4.5 6 7.5 9 \
--ofile  /mnt/meteo0/data/simmonds/dbirving/temp/sf-composite_wave7phase.png \
--subplot_headings phase_9_to_19 phase_29_to_39 phase_43_to_52 phase_9_to_19 phase_29_to_39 phase_43_to_52 \
--figure_size 16 9 \
--output_projection PlateCarree_Dateline PlateCarree_Dateline PlateCarree_Dateline SouthPolarStereo SouthPolarStereo SouthPolarStereo
